### ISSUE TITLE
Wrong styles with chart type Colored Bar

### ISSUE THREAD

**Issue by bia-effcreativve** [ChartIQ/Charting-Library---AngularJS-Seed-Project#14]
Hi, i have this issue in ChartIQ v3.0.5.

![](https://w3tls.net/8M1Xou9161b8dee506966225107202b051d1bf.png)

**Comment by NachoMoment** [comment]
Hi @bia-effcreativve,
So, colored bar charts take their color based on the close versus the previous close (not close vs. open like on a candle chart). The reason the bars you are pointing out are grey is because their close is neither higher nor lower than the previous close. This is an industry standard.
It does look like the grey bars are thinner than the colored bars in your screen shot but I'm not seeing this issue in the most recent version of the library. If you are still seeing a difference in thickness of the bars after upgrading to a more recent version then feel free to submit a support ticket to dev@chartiq.com
